### Phone Login
POST http://localhost:3000/api/v1/auth/phone
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166"
}

### Code trade
POST http://localhost:3000/api/v1/auth/token
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166",
  "token": "750007"
}