### Phone SignUp
POST {{host}}/auth/signup
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166",
  "password": "test123"
}

### Phone SignIn
POST {{host}}/auth/signin
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166",
  "password": "test123"
}

> {%
  client.global.set("token", response.body.session.access_token);
  client.global.set("refreshToken", response.body.session.refresh_token);
%}

### Phone Login
POST {{host}}/auth/phone
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166"
}

### Code trade
POST {{host}}/auth/token
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166",
  "token": "486816"
}

### Get logged user
GET {{host}}/auth/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Refresh token
POST {{host}}/auth/refresh-token
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
  client.global.set("token", response.body.session.access_token);
  client.global.set("refreshToken", response.body.session.refresh_token);
%}

### Logout
GET {{host}}/auth/logout
Accept: application/json