### Phone SignUp
POST http://localhost:3000/api/v1/auth/signup
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166",
  "password": "test"
}

### Phone Login
POST http://localhost:3000/api/v1/auth/phone
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166"
}

### Code trade
POST http://localhost:3000/api/v1/auth/token
Accept: application/json
Content-Type: application/json

{
  "phone": "+5517991449166",
  "token": "486816"
}

### Get logged user
GET http://localhost:3000/api/v1/auth/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjY3NTkwMzYwLCJzdWIiOiJiMTU2ODQ3Yi1jODVkLTQ5YjItYmE1MC05ZTU3MmExOThjNDEiLCJlbWFpbCI6IiIsInBob25lIjoiNTUxNzk5MTQ0OTE2NiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6InBob25lIiwicHJvdmlkZXJzIjpbInBob25lIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzZXNzaW9uX2lkIjoiZGQ1NWJiZGEtOWEyNC00YzAwLWEzYzItMGRkZmVjN2VmOWI0In0.y0FvZhquEij4oHSsRii_AM1Qj1BNgM7zQteLe7qpX_Q

### Refresh token
POST http://localhost:3000/api/v1/auth/refresh-token
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "Tp8PjgDlBRwER4TDitMvwg"
}

### Logout
GET http://localhost:3000/api/v1/auth/logout
Accept: application/json