### List root categories
GET {{host}}/category
Accept: application/json

### List subcategories
GET {{host}}/category/subcategory?parentId=80508dc8-d7d9-44d5-8021-71b31bd38ab1
Accept: application/json