### Get locations
GET {{host}}/location
Accept: application/json
Authorization: Bearer {{token}}

### Update a user
POST {{host}}/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "feeda104-b021-4a98-a72b-ac6c99a27883",
  "full_name": "John Doe",
  "avatar_url": "https://img.estadao.com.br/thumbs/640/resources/jpg/4/3/1651264747334.jpg",
  "website": "https://www.linkedin.com/in/marioteik"
}